# Generated by Django 5.0.1 on 2024-03-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('details', models.TextField()),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('Acer', 'Acer'), ('Asus', 'Asus')], max_length=7)),
                ('category', models.CharField(choices=[('Mobiles', 'Mobiles'), ('TVs', 'TVs'), ('Laptops', 'Laptops'), ('Home Appliances', 'Home Appliances')], max_length=15)),
                ('is_active', models.BooleanField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
