# Generated by Django 5.0.1 on 2024-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_table',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
